name: Cron Example
on:
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: cron-example

    steps:
    - uses: actions/checkout@v2

   

    # set up nodejs
    - name: Setup Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: "12.x"
    #install yarn
    - name: Install Yarn
      run: npm install -g yarn

    #install laibraries
    - name: Install Dependencies
      run: yarn install --frozen-lockfile
    #run tests (cucumber)
    - name: Run tests
      run: yarn test