name: Pull Request Example
on:
  pull_request:
  # Trigger on pull request eventsbranches
    defaults:
      run:
        working-directory: typescript-project
    branches:
      - master
    paths:
      - typescript-project/** # Only run for changes in the typescript-project directory
    
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: typescript-project

    steps:
    - uses: actions/checkout@v2

   

    # set up nodejs
    - name: Setup Node.js 12
      uses: actions/setup-node@v2
      
      with:
        node-version: "12.x"
        cache: "npm" # Enable caching for npm dependencies

    #install yarn
    - name: Install Yarn
      run: npm install -g yarn

    #install laibraries
    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    #run linting
    - name: Run linting
      run: yarn lint

    # Compile code
    - name: Build Project
      run: yarn build
       

    #run tests (cucumber)
    - name: Run tests
      run: yarn test